board/urls.py
from django.urls import path

from . import views

app_name = 'board'
urlpatterns = [
    path('', views.mainView, name='mainview'),
    path('<int:pk>/', views.detailView, name='detail'),
    path('create/', views.createPost, name='createpost'),
    path('<int:pk>/delete/', views.deletePost, name='deletepost'),
    path('<int:pk>/update/', views.updatePost, name='updatepost'),
    path('<int:pk>/deletecomments/<int:cid>', views.deleteComment, name='deletecomment'),
    path('<int:pk>/updatecomments/<int:cid>', views.updateComment, name='updatecomment'),
]

myboard/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('board.urls')),
    path('admin/', admin.site.urls),
]

board/models.py
import datetime

from django.db import models
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    mod_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.comment_text

board/forms.py
from django import forms

from .models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text')

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

board/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Post, Comment
from .forms import PostForm, CommentForm

from django.http import HttpResponse


def mainView(request):
    posts = {"posts": Post.objects.all()}
    return render(request, "board/index.html", posts)


def detailView(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.text = form.cleaned_data['text']
            comment.save()
        return redirect("board:detail", pk=post.id)

    comments = Comment.objects.filter(post=post)
    form = CommentForm()
    return render(request, "board/detail.html", {"post": post, "comments": comments, "form": form})


def createPost(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            #post = form.save(commit=False)
            post = form.save()
        return redirect("board:detail", pk=post.id)
    else:
        form = PostForm()
        return render(request, "board/newpost.html", {"form": form})

def updatePost(request, pk):
    origin_post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=origin_post)
        if form.is_valid():
            #post = form.save(commit=False)
            post = form.save(commit=False)
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['text']
            post.save()
            return redirect("board:detail", pk=pk)
    form = PostForm(instance=origin_post)
    return render(request, "board/newpost.html", {"form": form})

def updateComment(request, pk, cid):
    post = get_object_or_404(Post, pk=pk)
    origin_comment = get_object_or_404(Comment, pk=cid)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=origin_comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.text = form.cleaned_data['text']
            comment.save()
        return redirect("board:detail", pk=post.id)

    comments = Comment.objects.filter(post=post)
    form = CommentForm(instance=origin_comment)
    return render(request, "board/detail.html", {"post": post, "comments": comments, "form": form})


def deletePost(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect("board:mainview")

def deleteComment(request, pk, cid):
    comment = get_object_or_404(Comment, pk=cid)
    comment.delete()
    return redirect("board:detail", pk=pk)

board/templates/board/detail.html
<h1><a href="{% url 'board:mainview' %}">홈</a></h1>
<h1>{{ post.title }}</h1>
<p>{{ post.text }}</p>
<p>{{ post.mod_date}}</p>

<p>
    <a href="{% url 'board:deletepost' post.id %}">삭제</a>
    <a href="{% url 'board:updatepost' post.id %}">수정</a>
</p>

<h3> 댓글 </h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.text }}
        <input type = "submit">
    </form>
<ul>
    {% for comment in comments %}
        <li>{{ comment.text }}</li>
        <form action="{% url 'board:deletecomment' post.id comment.id %}" method="POST">
            {% csrf_token %}
            <input type = "submit" value = "삭제">
        </form>
        <input type = "submit" value = "수정" onClick="location.href='{% url 'board:updatecomment' post.id comment.id %}'">
    {% endfor %}
</ul>

board/templates/board/index.html
<h1>프로그라피 게시판</h1>
<a href="{% url 'board:createpost' %}">글쓰기</a>

{% if posts %}
    <ul>
        {% for post in posts %}
            <li><a href="{% url 'board:detail' post.id %}">{{ post }}</a></li>
        {% endfor %}
    </ul>
{% endif %}

board/templates/board/newpost.html
<form action="" method="post">
    {% csrf_token %}
    <p>
        <label for="title">제목</label>
        {{ form.title }}
    </p>
    <p><label for="text">내용</label></p>
    {{ form.text }}
    <p><input type = "submit"></p>
</form>